### PR TITLE
an_parks_cleanup

### PR DESCRIPTION
**Pull request by alyssa-nycum-imprivata**
1) git fetch --all
2) git checkout an_parks_cleanup
3) verify that checkmarks clear once search park button is clicked
4) added more save park button styling

### CODE REVIEW

**Comment by mKroogz** [comment]
That checkbox thing is so cool.  Looks great!

**Comment by alyssa-nycum-imprivata** [comment]
I just added one more thing. You should be able to click the checkboxes you want and then press enter on your keyboard without having to click the search button.

**Comment by kwohl** [comment]
looks great!!

**Comment by CoopNich** [comment]
Works for me!

**Pull request merged**
